services:
  envoy:
    build: ./App/envoy
    ports:
      - '9901:9901'
      - '8080:8080'
      - '9090:9090'
    networks:
      - next-envoy
      - envoy-go

  app-frontend:
    build:
      context: ./App
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./App:/app
    restart: always
    networks:
      - next-envoy
  
  home:
    build:
      context: ./Home
      target: development
    ports:
      - 5000:5000
    volumes:
      - ./Home:/app
    restart: always

networks:
  next-envoy:
  envoy-go:
  go-db:

Backend:

version: "3"
backend-service:
  app:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env 