services:
  app-frontend:
    build:
      context: ./App
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./App:/app
    restart: always
    depends_on:
      - backend
    networks:
      - next-envoy
  
  home:
    build:
      context: ./Home
      target: development
    ports:
      - 5000:5000
    volumes:
      - ./Home:/app
    restart: always

  backend:
    build: ./CommonServer
    ports:
      - "9000:9000"
    env_file:
      - ./CommonServer/.env 

networks:
  next-envoy:
  envoy-go:
  go-db:
